#!/usr/bin/env bash

abs_astra_dir="$(dirname "$(realpath "$0")")"

GUILE_LOAD_PATH="${abs_astra_dir}${GUILE_LOAD_PATH:+:}${GUILE_LOAD_PATH}"
GUIX_PACKAGE_PATH="${abs_astra_dir}${GUIX_PACKAGE_PATH:+:}${GUIX_PACKAGE_PATH}"

export GUILE_LOAD_PATH GUIX_PACKAGE_PATH

exec "$@"
