#!/bin/sh


export XDG_CURRENT_DESKTOP=Hyprland
export XDG_SESSION_DESKTOP=Hyprland
export XDG_SESSION_TYPE=wayland

export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_QPA_PLATFORM="wayland;xcb"
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export QT_QPA_PLATFORMTHEME=qt5ct

export SHELL=fish
export TERM=kitty
#export EDITOR='emacsclient -nw'
#export VISUAL='emacsclient -c'

export BROWSER=firefox
export MOZ_ENABLE_WAYLAND=1

export _JAVA_AWT_WM_NONREPARENTING=1
export CLUTTER_BACKEND=wayland
#export GDK_BACKEND=wayland


# To add nix packages to the path
source '/run/current-system/profile/etc/profile.d/nix.sh'

export PATH="/home/egiorgis/.config/hypr/scripts/:/home/egiorgis/.config/emacs/bin:/home/egiorgis/.local/bin:$PATH"

exec Hyprland
